spring:
  application:
    name: provider
  servlet:
    multipart:
      enabled: true
      max-request-size: 2048MB
      max-file-size: 2048MB

server:
  port: 8111

# CSE RPC 的配置项
# 应用名称
APPLICATION_ID: SpringCloud-ServiceComb
# 微服务名称和版本号，微服务名称使用Spring Cloud的名称
service_description:
  name: ${spring.application.name}
  version: 1.0.1
  environment: development
# 服务中心的地址
servicecomb:
  service:
    registry:
      address: http://106.12.97.129:30100
      instance:
        watch: false
  # 对外发布的地址，端口号使用server.port
  rest:
    address: 0.0.0.0:${server.port}
  # 线下开发，关闭监控数据上报
  monitor:
    client:
      enable: false

#华为OBS文件上传配置
huawei:
  obs:
    ak: 3TWL7VJQ4IM45X3DAMLF
    sk: i1aCblcgP4ZyoUwBHZnWd4rJCb5skN2Ya0LzSix5
    end-point: obs.cn-north-1.myhuaweicloud.com
    https-only: true
    socket-timeout: 30000
    connection-timeout: 10000
