spring:
  application:
    name: provider
  datasource:
    url: jdbc:mysql:///hoolink-face?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: qwe12356
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8111

# CSE RPC 的配置项
# 应用名称
APPLICATION_ID: SpringCloud-ServiceComb
# 微服务名称和版本号，微服务名称使用Spring Cloud的名称
service_description:
  name: ${spring.application.name}
  version: 1.0.1
  environment: development
# 服务中心的地址
servicecomb:
  service:
    registry:
      address: http://106.12.97.129:30100
      instance:
        watch: false
  # 对外发布的地址，端口号使用server.port
  rest:
    address: 0.0.0.0:${server.port}
  # 线下开发，关闭监控数据上报
  monitor:
    client:
      enable: false

  #配置文件上传
  uploads:
    directory: tmp
    maxSize: -1

  #配置请求跨域
  cors:
    enabled: true
    origin: "*"
    allowCredentials: false
    allowedMethod: PUT,DELETE,POST,GET
    allowedHeader: "*"
    maxAge: 3600

  # 处理链配置
  handler:
    chain:
      Provider:
        default: qps-flowcontrol-provider
      Consumer:
        default: qps-flowcontrol-consumer,loadbalance,fault-injection-consumer

#华为OBS文件上传配置
huawei:
  obs:
    end-point: obs.cn-north-1.myhuaweicloud.com
    https-only: true
    socket-timeout: 30000
    connection-timeout: 10000
    sk: i1aCblcgP4ZyoUwBHZnWd4rJCb5skN2Ya0LzSix5
    ak: 3TWL7VJQ4IM45X3DAMLF
  dis:
    access-key: 3TWL7VJQ4IM45X3DAMLF
    secret-key: i1aCblcgP4ZyoUwBHZnWd4rJCb5skN2Ya0LzSix5
    region: cn-north-1
    end-point: https://dis.cn-north-1.myhuaweicloud.com:20004
    project-id: 3c9ff3e423154e03bb8d65cfc5ae0d67
  frs:
    access-key: 3TWL7VJQ4IM45X3DAMLF
    secret-key: i1aCblcgP4ZyoUwBHZnWd4rJCb5skN2Ya0LzSix5
    region: cn-north-1
    project-id: 3c9ff3e423154e03bb8d65cfc5ae0d67
    end-point: https://face.cn-north-1.myhuaweicloud.com
    api-version: v1
    service-name: frs

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.sample.servicecomb.provider.model
