spring:
  application:
    name: rest-rest
  datasource:
    url: jdbc:mysql:///hoolink-face?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: qwe12356
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8115

# CSE RPC 的配置项
# 应用名称
APPLICATION_ID: SpringCloud-ServiceComb
# 微服务名称和版本号，微服务名称使用Spring Cloud的名称
service_description:
  name: ${spring.application.name}
  version: 1.0.1
  environment: development
# 服务中心的地址
servicecomb:
  service:
    registry:
      address: http://106.12.97.129:30100
      instance:
        watch: false
  # 对外发布的地址，端口号使用server.port
  rest:
    address: 0.0.0.0:${server.port}
  # 线下开发，关闭监控数据上报
  monitor:
    client:
      enable: false

  #配置请求跨域
  cors:
    enabled: true
    origin: "*"
    allowCredentials: false
    allowedMethod: PUT,DELETE,POST,GET
    allowedHeader: "*"
    maxAge: 3600

  # 处理链配置
  handler:
    chain:
      Provider:
        default: qps-flowcontrol-provider
      Consumer:
        default: qps-flowcontrol-consumer,loadbalance,fault-injection-consumer