package com.sample.servicecomb.provider.dao;

import com.sample.servicecomb.provider.model.BaseObs;
import com.sample.servicecomb.provider.model.BaseObsExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface BaseObsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_obs
     *
     * @mbg.generated
     */
    long countByExample(BaseObsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_obs
     *
     * @mbg.generated
     */
    int deleteByExample(BaseObsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_obs
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_obs
     *
     * @mbg.generated
     */
    int insert(BaseObs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_obs
     *
     * @mbg.generated
     */
    int insertSelective(BaseObs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_obs
     *
     * @mbg.generated
     */
    List<BaseObs> selectByExample(BaseObsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_obs
     *
     * @mbg.generated
     */
    BaseObs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_obs
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BaseObs record, @Param("example") BaseObsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_obs
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BaseObs record, @Param("example") BaseObsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_obs
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BaseObs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_obs
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BaseObs record);
}