package com.sample.servicecomb.provider.dao;

import com.sample.servicecomb.provider.model.FaceInfo;
import com.sample.servicecomb.provider.model.FaceInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface FaceInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_info
     *
     * @mbg.generated
     */
    long countByExample(FaceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_info
     *
     * @mbg.generated
     */
    int deleteByExample(FaceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_info
     *
     * @mbg.generated
     */
    int insert(FaceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_info
     *
     * @mbg.generated
     */
    int insertSelective(FaceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_info
     *
     * @mbg.generated
     */
    List<FaceInfo> selectByExample(FaceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_info
     *
     * @mbg.generated
     */
    FaceInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FaceInfo record, @Param("example") FaceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FaceInfo record, @Param("example") FaceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FaceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FaceInfo record);
}