package com.sample.servicecomb.provider.dao;

import com.sample.servicecomb.provider.model.FaceHis;
import com.sample.servicecomb.provider.model.FaceHisExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface FaceHisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_his
     *
     * @mbg.generated
     */
    long countByExample(FaceHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_his
     *
     * @mbg.generated
     */
    int deleteByExample(FaceHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_his
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_his
     *
     * @mbg.generated
     */
    int insert(FaceHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_his
     *
     * @mbg.generated
     */
    int insertSelective(FaceHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_his
     *
     * @mbg.generated
     */
    List<FaceHis> selectByExample(FaceHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_his
     *
     * @mbg.generated
     */
    FaceHis selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_his
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FaceHis record, @Param("example") FaceHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_his
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FaceHis record, @Param("example") FaceHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_his
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FaceHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_his
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FaceHis record);
}