package com.sample.servicecomb.provider.model;

import java.io.Serializable;
import java.util.Date;

public class BaseObs implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_obs.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_obs.bucket_name
     *
     * @mbg.generated
     */
    private String bucketName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_obs.object_key
     *
     * @mbg.generated
     */
    private String objectKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_obs.etag
     *
     * @mbg.generated
     */
    private String etag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_obs.version_id
     *
     * @mbg.generated
     */
    private String versionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_obs.creater
     *
     * @mbg.generated
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_obs.created
     *
     * @mbg.generated
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_obs.file_name
     *
     * @mbg.generated
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_obs.file_ext_name
     *
     * @mbg.generated
     */
    private String fileExtName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_obs.file_size
     *
     * @mbg.generated
     */
    private Long fileSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_obs.updater
     *
     * @mbg.generated
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_obs.updated
     *
     * @mbg.generated
     */
    private Date updated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_obs.enable
     *
     * @mbg.generated
     */
    private Boolean enable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_obs.obs_domain
     *
     * @mbg.generated
     */
    private String obsDomain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_obs.object_url
     *
     * @mbg.generated
     */
    private String objectUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_obs
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_obs.id
     *
     * @return the value of base_obs.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_obs.id
     *
     * @param id the value for base_obs.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_obs.bucket_name
     *
     * @return the value of base_obs.bucket_name
     *
     * @mbg.generated
     */
    public String getBucketName() {
        return bucketName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_obs.bucket_name
     *
     * @param bucketName the value for base_obs.bucket_name
     *
     * @mbg.generated
     */
    public void setBucketName(String bucketName) {
        this.bucketName = bucketName == null ? null : bucketName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_obs.object_key
     *
     * @return the value of base_obs.object_key
     *
     * @mbg.generated
     */
    public String getObjectKey() {
        return objectKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_obs.object_key
     *
     * @param objectKey the value for base_obs.object_key
     *
     * @mbg.generated
     */
    public void setObjectKey(String objectKey) {
        this.objectKey = objectKey == null ? null : objectKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_obs.etag
     *
     * @return the value of base_obs.etag
     *
     * @mbg.generated
     */
    public String getEtag() {
        return etag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_obs.etag
     *
     * @param etag the value for base_obs.etag
     *
     * @mbg.generated
     */
    public void setEtag(String etag) {
        this.etag = etag == null ? null : etag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_obs.version_id
     *
     * @return the value of base_obs.version_id
     *
     * @mbg.generated
     */
    public String getVersionId() {
        return versionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_obs.version_id
     *
     * @param versionId the value for base_obs.version_id
     *
     * @mbg.generated
     */
    public void setVersionId(String versionId) {
        this.versionId = versionId == null ? null : versionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_obs.creater
     *
     * @return the value of base_obs.creater
     *
     * @mbg.generated
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_obs.creater
     *
     * @param creater the value for base_obs.creater
     *
     * @mbg.generated
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_obs.created
     *
     * @return the value of base_obs.created
     *
     * @mbg.generated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_obs.created
     *
     * @param created the value for base_obs.created
     *
     * @mbg.generated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_obs.file_name
     *
     * @return the value of base_obs.file_name
     *
     * @mbg.generated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_obs.file_name
     *
     * @param fileName the value for base_obs.file_name
     *
     * @mbg.generated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_obs.file_ext_name
     *
     * @return the value of base_obs.file_ext_name
     *
     * @mbg.generated
     */
    public String getFileExtName() {
        return fileExtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_obs.file_ext_name
     *
     * @param fileExtName the value for base_obs.file_ext_name
     *
     * @mbg.generated
     */
    public void setFileExtName(String fileExtName) {
        this.fileExtName = fileExtName == null ? null : fileExtName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_obs.file_size
     *
     * @return the value of base_obs.file_size
     *
     * @mbg.generated
     */
    public Long getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_obs.file_size
     *
     * @param fileSize the value for base_obs.file_size
     *
     * @mbg.generated
     */
    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_obs.updater
     *
     * @return the value of base_obs.updater
     *
     * @mbg.generated
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_obs.updater
     *
     * @param updater the value for base_obs.updater
     *
     * @mbg.generated
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_obs.updated
     *
     * @return the value of base_obs.updated
     *
     * @mbg.generated
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_obs.updated
     *
     * @param updated the value for base_obs.updated
     *
     * @mbg.generated
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_obs.enable
     *
     * @return the value of base_obs.enable
     *
     * @mbg.generated
     */
    public Boolean getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_obs.enable
     *
     * @param enable the value for base_obs.enable
     *
     * @mbg.generated
     */
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_obs.obs_domain
     *
     * @return the value of base_obs.obs_domain
     *
     * @mbg.generated
     */
    public String getObsDomain() {
        return obsDomain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_obs.obs_domain
     *
     * @param obsDomain the value for base_obs.obs_domain
     *
     * @mbg.generated
     */
    public void setObsDomain(String obsDomain) {
        this.obsDomain = obsDomain == null ? null : obsDomain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_obs.object_url
     *
     * @return the value of base_obs.object_url
     *
     * @mbg.generated
     */
    public String getObjectUrl() {
        return objectUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_obs.object_url
     *
     * @param objectUrl the value for base_obs.object_url
     *
     * @mbg.generated
     */
    public void setObjectUrl(String objectUrl) {
        this.objectUrl = objectUrl == null ? null : objectUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_obs
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BaseObs other = (BaseObs) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getBucketName() == null ? other.getBucketName() == null : this.getBucketName().equals(other.getBucketName()))
            && (this.getObjectKey() == null ? other.getObjectKey() == null : this.getObjectKey().equals(other.getObjectKey()))
            && (this.getEtag() == null ? other.getEtag() == null : this.getEtag().equals(other.getEtag()))
            && (this.getVersionId() == null ? other.getVersionId() == null : this.getVersionId().equals(other.getVersionId()))
            && (this.getCreater() == null ? other.getCreater() == null : this.getCreater().equals(other.getCreater()))
            && (this.getCreated() == null ? other.getCreated() == null : this.getCreated().equals(other.getCreated()))
            && (this.getFileName() == null ? other.getFileName() == null : this.getFileName().equals(other.getFileName()))
            && (this.getFileExtName() == null ? other.getFileExtName() == null : this.getFileExtName().equals(other.getFileExtName()))
            && (this.getFileSize() == null ? other.getFileSize() == null : this.getFileSize().equals(other.getFileSize()))
            && (this.getUpdater() == null ? other.getUpdater() == null : this.getUpdater().equals(other.getUpdater()))
            && (this.getUpdated() == null ? other.getUpdated() == null : this.getUpdated().equals(other.getUpdated()))
            && (this.getEnable() == null ? other.getEnable() == null : this.getEnable().equals(other.getEnable()))
            && (this.getObsDomain() == null ? other.getObsDomain() == null : this.getObsDomain().equals(other.getObsDomain()))
            && (this.getObjectUrl() == null ? other.getObjectUrl() == null : this.getObjectUrl().equals(other.getObjectUrl()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_obs
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getBucketName() == null) ? 0 : getBucketName().hashCode());
        result = prime * result + ((getObjectKey() == null) ? 0 : getObjectKey().hashCode());
        result = prime * result + ((getEtag() == null) ? 0 : getEtag().hashCode());
        result = prime * result + ((getVersionId() == null) ? 0 : getVersionId().hashCode());
        result = prime * result + ((getCreater() == null) ? 0 : getCreater().hashCode());
        result = prime * result + ((getCreated() == null) ? 0 : getCreated().hashCode());
        result = prime * result + ((getFileName() == null) ? 0 : getFileName().hashCode());
        result = prime * result + ((getFileExtName() == null) ? 0 : getFileExtName().hashCode());
        result = prime * result + ((getFileSize() == null) ? 0 : getFileSize().hashCode());
        result = prime * result + ((getUpdater() == null) ? 0 : getUpdater().hashCode());
        result = prime * result + ((getUpdated() == null) ? 0 : getUpdated().hashCode());
        result = prime * result + ((getEnable() == null) ? 0 : getEnable().hashCode());
        result = prime * result + ((getObsDomain() == null) ? 0 : getObsDomain().hashCode());
        result = prime * result + ((getObjectUrl() == null) ? 0 : getObjectUrl().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_obs
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", bucketName=").append(bucketName);
        sb.append(", objectKey=").append(objectKey);
        sb.append(", etag=").append(etag);
        sb.append(", versionId=").append(versionId);
        sb.append(", creater=").append(creater);
        sb.append(", created=").append(created);
        sb.append(", fileName=").append(fileName);
        sb.append(", fileExtName=").append(fileExtName);
        sb.append(", fileSize=").append(fileSize);
        sb.append(", updater=").append(updater);
        sb.append(", updated=").append(updated);
        sb.append(", enable=").append(enable);
        sb.append(", obsDomain=").append(obsDomain);
        sb.append(", objectUrl=").append(objectUrl);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}