package com.sample.servicecomb.provider.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BaseObsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_obs
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_obs
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_obs
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_obs
     *
     * @mbg.generated
     */
    public BaseObsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_obs
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_obs
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_obs
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_obs
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_obs
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_obs
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_obs
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_obs
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_obs
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_obs
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table base_obs
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andBucketNameIsNull() {
            addCriterion("bucket_name is null");
            return (Criteria) this;
        }

        public Criteria andBucketNameIsNotNull() {
            addCriterion("bucket_name is not null");
            return (Criteria) this;
        }

        public Criteria andBucketNameEqualTo(String value) {
            addCriterion("bucket_name =", value, "bucketName");
            return (Criteria) this;
        }

        public Criteria andBucketNameNotEqualTo(String value) {
            addCriterion("bucket_name <>", value, "bucketName");
            return (Criteria) this;
        }

        public Criteria andBucketNameGreaterThan(String value) {
            addCriterion("bucket_name >", value, "bucketName");
            return (Criteria) this;
        }

        public Criteria andBucketNameGreaterThanOrEqualTo(String value) {
            addCriterion("bucket_name >=", value, "bucketName");
            return (Criteria) this;
        }

        public Criteria andBucketNameLessThan(String value) {
            addCriterion("bucket_name <", value, "bucketName");
            return (Criteria) this;
        }

        public Criteria andBucketNameLessThanOrEqualTo(String value) {
            addCriterion("bucket_name <=", value, "bucketName");
            return (Criteria) this;
        }

        public Criteria andBucketNameLike(String value) {
            addCriterion("bucket_name like", value, "bucketName");
            return (Criteria) this;
        }

        public Criteria andBucketNameNotLike(String value) {
            addCriterion("bucket_name not like", value, "bucketName");
            return (Criteria) this;
        }

        public Criteria andBucketNameIn(List<String> values) {
            addCriterion("bucket_name in", values, "bucketName");
            return (Criteria) this;
        }

        public Criteria andBucketNameNotIn(List<String> values) {
            addCriterion("bucket_name not in", values, "bucketName");
            return (Criteria) this;
        }

        public Criteria andBucketNameBetween(String value1, String value2) {
            addCriterion("bucket_name between", value1, value2, "bucketName");
            return (Criteria) this;
        }

        public Criteria andBucketNameNotBetween(String value1, String value2) {
            addCriterion("bucket_name not between", value1, value2, "bucketName");
            return (Criteria) this;
        }

        public Criteria andObjectKeyIsNull() {
            addCriterion("object_key is null");
            return (Criteria) this;
        }

        public Criteria andObjectKeyIsNotNull() {
            addCriterion("object_key is not null");
            return (Criteria) this;
        }

        public Criteria andObjectKeyEqualTo(String value) {
            addCriterion("object_key =", value, "objectKey");
            return (Criteria) this;
        }

        public Criteria andObjectKeyNotEqualTo(String value) {
            addCriterion("object_key <>", value, "objectKey");
            return (Criteria) this;
        }

        public Criteria andObjectKeyGreaterThan(String value) {
            addCriterion("object_key >", value, "objectKey");
            return (Criteria) this;
        }

        public Criteria andObjectKeyGreaterThanOrEqualTo(String value) {
            addCriterion("object_key >=", value, "objectKey");
            return (Criteria) this;
        }

        public Criteria andObjectKeyLessThan(String value) {
            addCriterion("object_key <", value, "objectKey");
            return (Criteria) this;
        }

        public Criteria andObjectKeyLessThanOrEqualTo(String value) {
            addCriterion("object_key <=", value, "objectKey");
            return (Criteria) this;
        }

        public Criteria andObjectKeyLike(String value) {
            addCriterion("object_key like", value, "objectKey");
            return (Criteria) this;
        }

        public Criteria andObjectKeyNotLike(String value) {
            addCriterion("object_key not like", value, "objectKey");
            return (Criteria) this;
        }

        public Criteria andObjectKeyIn(List<String> values) {
            addCriterion("object_key in", values, "objectKey");
            return (Criteria) this;
        }

        public Criteria andObjectKeyNotIn(List<String> values) {
            addCriterion("object_key not in", values, "objectKey");
            return (Criteria) this;
        }

        public Criteria andObjectKeyBetween(String value1, String value2) {
            addCriterion("object_key between", value1, value2, "objectKey");
            return (Criteria) this;
        }

        public Criteria andObjectKeyNotBetween(String value1, String value2) {
            addCriterion("object_key not between", value1, value2, "objectKey");
            return (Criteria) this;
        }

        public Criteria andEtagIsNull() {
            addCriterion("etag is null");
            return (Criteria) this;
        }

        public Criteria andEtagIsNotNull() {
            addCriterion("etag is not null");
            return (Criteria) this;
        }

        public Criteria andEtagEqualTo(String value) {
            addCriterion("etag =", value, "etag");
            return (Criteria) this;
        }

        public Criteria andEtagNotEqualTo(String value) {
            addCriterion("etag <>", value, "etag");
            return (Criteria) this;
        }

        public Criteria andEtagGreaterThan(String value) {
            addCriterion("etag >", value, "etag");
            return (Criteria) this;
        }

        public Criteria andEtagGreaterThanOrEqualTo(String value) {
            addCriterion("etag >=", value, "etag");
            return (Criteria) this;
        }

        public Criteria andEtagLessThan(String value) {
            addCriterion("etag <", value, "etag");
            return (Criteria) this;
        }

        public Criteria andEtagLessThanOrEqualTo(String value) {
            addCriterion("etag <=", value, "etag");
            return (Criteria) this;
        }

        public Criteria andEtagLike(String value) {
            addCriterion("etag like", value, "etag");
            return (Criteria) this;
        }

        public Criteria andEtagNotLike(String value) {
            addCriterion("etag not like", value, "etag");
            return (Criteria) this;
        }

        public Criteria andEtagIn(List<String> values) {
            addCriterion("etag in", values, "etag");
            return (Criteria) this;
        }

        public Criteria andEtagNotIn(List<String> values) {
            addCriterion("etag not in", values, "etag");
            return (Criteria) this;
        }

        public Criteria andEtagBetween(String value1, String value2) {
            addCriterion("etag between", value1, value2, "etag");
            return (Criteria) this;
        }

        public Criteria andEtagNotBetween(String value1, String value2) {
            addCriterion("etag not between", value1, value2, "etag");
            return (Criteria) this;
        }

        public Criteria andVersionIdIsNull() {
            addCriterion("version_id is null");
            return (Criteria) this;
        }

        public Criteria andVersionIdIsNotNull() {
            addCriterion("version_id is not null");
            return (Criteria) this;
        }

        public Criteria andVersionIdEqualTo(String value) {
            addCriterion("version_id =", value, "versionId");
            return (Criteria) this;
        }

        public Criteria andVersionIdNotEqualTo(String value) {
            addCriterion("version_id <>", value, "versionId");
            return (Criteria) this;
        }

        public Criteria andVersionIdGreaterThan(String value) {
            addCriterion("version_id >", value, "versionId");
            return (Criteria) this;
        }

        public Criteria andVersionIdGreaterThanOrEqualTo(String value) {
            addCriterion("version_id >=", value, "versionId");
            return (Criteria) this;
        }

        public Criteria andVersionIdLessThan(String value) {
            addCriterion("version_id <", value, "versionId");
            return (Criteria) this;
        }

        public Criteria andVersionIdLessThanOrEqualTo(String value) {
            addCriterion("version_id <=", value, "versionId");
            return (Criteria) this;
        }

        public Criteria andVersionIdLike(String value) {
            addCriterion("version_id like", value, "versionId");
            return (Criteria) this;
        }

        public Criteria andVersionIdNotLike(String value) {
            addCriterion("version_id not like", value, "versionId");
            return (Criteria) this;
        }

        public Criteria andVersionIdIn(List<String> values) {
            addCriterion("version_id in", values, "versionId");
            return (Criteria) this;
        }

        public Criteria andVersionIdNotIn(List<String> values) {
            addCriterion("version_id not in", values, "versionId");
            return (Criteria) this;
        }

        public Criteria andVersionIdBetween(String value1, String value2) {
            addCriterion("version_id between", value1, value2, "versionId");
            return (Criteria) this;
        }

        public Criteria andVersionIdNotBetween(String value1, String value2) {
            addCriterion("version_id not between", value1, value2, "versionId");
            return (Criteria) this;
        }

        public Criteria andCreaterIsNull() {
            addCriterion("creater is null");
            return (Criteria) this;
        }

        public Criteria andCreaterIsNotNull() {
            addCriterion("creater is not null");
            return (Criteria) this;
        }

        public Criteria andCreaterEqualTo(String value) {
            addCriterion("creater =", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotEqualTo(String value) {
            addCriterion("creater <>", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThan(String value) {
            addCriterion("creater >", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThanOrEqualTo(String value) {
            addCriterion("creater >=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThan(String value) {
            addCriterion("creater <", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThanOrEqualTo(String value) {
            addCriterion("creater <=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLike(String value) {
            addCriterion("creater like", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotLike(String value) {
            addCriterion("creater not like", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterIn(List<String> values) {
            addCriterion("creater in", values, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotIn(List<String> values) {
            addCriterion("creater not in", values, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterBetween(String value1, String value2) {
            addCriterion("creater between", value1, value2, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotBetween(String value1, String value2) {
            addCriterion("creater not between", value1, value2, "creater");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNull() {
            addCriterion("created is null");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNotNull() {
            addCriterion("created is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedEqualTo(Date value) {
            addCriterion("created =", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotEqualTo(Date value) {
            addCriterion("created <>", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThan(Date value) {
            addCriterion("created >", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("created >=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThan(Date value) {
            addCriterion("created <", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThanOrEqualTo(Date value) {
            addCriterion("created <=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedIn(List<Date> values) {
            addCriterion("created in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotIn(List<Date> values) {
            addCriterion("created not in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedBetween(Date value1, Date value2) {
            addCriterion("created between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotBetween(Date value1, Date value2) {
            addCriterion("created not between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andFileNameIsNull() {
            addCriterion("file_name is null");
            return (Criteria) this;
        }

        public Criteria andFileNameIsNotNull() {
            addCriterion("file_name is not null");
            return (Criteria) this;
        }

        public Criteria andFileNameEqualTo(String value) {
            addCriterion("file_name =", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameNotEqualTo(String value) {
            addCriterion("file_name <>", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameGreaterThan(String value) {
            addCriterion("file_name >", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameGreaterThanOrEqualTo(String value) {
            addCriterion("file_name >=", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameLessThan(String value) {
            addCriterion("file_name <", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameLessThanOrEqualTo(String value) {
            addCriterion("file_name <=", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameLike(String value) {
            addCriterion("file_name like", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameNotLike(String value) {
            addCriterion("file_name not like", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameIn(List<String> values) {
            addCriterion("file_name in", values, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameNotIn(List<String> values) {
            addCriterion("file_name not in", values, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameBetween(String value1, String value2) {
            addCriterion("file_name between", value1, value2, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameNotBetween(String value1, String value2) {
            addCriterion("file_name not between", value1, value2, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileExtNameIsNull() {
            addCriterion("file_ext_name is null");
            return (Criteria) this;
        }

        public Criteria andFileExtNameIsNotNull() {
            addCriterion("file_ext_name is not null");
            return (Criteria) this;
        }

        public Criteria andFileExtNameEqualTo(String value) {
            addCriterion("file_ext_name =", value, "fileExtName");
            return (Criteria) this;
        }

        public Criteria andFileExtNameNotEqualTo(String value) {
            addCriterion("file_ext_name <>", value, "fileExtName");
            return (Criteria) this;
        }

        public Criteria andFileExtNameGreaterThan(String value) {
            addCriterion("file_ext_name >", value, "fileExtName");
            return (Criteria) this;
        }

        public Criteria andFileExtNameGreaterThanOrEqualTo(String value) {
            addCriterion("file_ext_name >=", value, "fileExtName");
            return (Criteria) this;
        }

        public Criteria andFileExtNameLessThan(String value) {
            addCriterion("file_ext_name <", value, "fileExtName");
            return (Criteria) this;
        }

        public Criteria andFileExtNameLessThanOrEqualTo(String value) {
            addCriterion("file_ext_name <=", value, "fileExtName");
            return (Criteria) this;
        }

        public Criteria andFileExtNameLike(String value) {
            addCriterion("file_ext_name like", value, "fileExtName");
            return (Criteria) this;
        }

        public Criteria andFileExtNameNotLike(String value) {
            addCriterion("file_ext_name not like", value, "fileExtName");
            return (Criteria) this;
        }

        public Criteria andFileExtNameIn(List<String> values) {
            addCriterion("file_ext_name in", values, "fileExtName");
            return (Criteria) this;
        }

        public Criteria andFileExtNameNotIn(List<String> values) {
            addCriterion("file_ext_name not in", values, "fileExtName");
            return (Criteria) this;
        }

        public Criteria andFileExtNameBetween(String value1, String value2) {
            addCriterion("file_ext_name between", value1, value2, "fileExtName");
            return (Criteria) this;
        }

        public Criteria andFileExtNameNotBetween(String value1, String value2) {
            addCriterion("file_ext_name not between", value1, value2, "fileExtName");
            return (Criteria) this;
        }

        public Criteria andFileSizeIsNull() {
            addCriterion("file_size is null");
            return (Criteria) this;
        }

        public Criteria andFileSizeIsNotNull() {
            addCriterion("file_size is not null");
            return (Criteria) this;
        }

        public Criteria andFileSizeEqualTo(Long value) {
            addCriterion("file_size =", value, "fileSize");
            return (Criteria) this;
        }

        public Criteria andFileSizeNotEqualTo(Long value) {
            addCriterion("file_size <>", value, "fileSize");
            return (Criteria) this;
        }

        public Criteria andFileSizeGreaterThan(Long value) {
            addCriterion("file_size >", value, "fileSize");
            return (Criteria) this;
        }

        public Criteria andFileSizeGreaterThanOrEqualTo(Long value) {
            addCriterion("file_size >=", value, "fileSize");
            return (Criteria) this;
        }

        public Criteria andFileSizeLessThan(Long value) {
            addCriterion("file_size <", value, "fileSize");
            return (Criteria) this;
        }

        public Criteria andFileSizeLessThanOrEqualTo(Long value) {
            addCriterion("file_size <=", value, "fileSize");
            return (Criteria) this;
        }

        public Criteria andFileSizeIn(List<Long> values) {
            addCriterion("file_size in", values, "fileSize");
            return (Criteria) this;
        }

        public Criteria andFileSizeNotIn(List<Long> values) {
            addCriterion("file_size not in", values, "fileSize");
            return (Criteria) this;
        }

        public Criteria andFileSizeBetween(Long value1, Long value2) {
            addCriterion("file_size between", value1, value2, "fileSize");
            return (Criteria) this;
        }

        public Criteria andFileSizeNotBetween(Long value1, Long value2) {
            addCriterion("file_size not between", value1, value2, "fileSize");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNull() {
            addCriterion("updater is null");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNotNull() {
            addCriterion("updater is not null");
            return (Criteria) this;
        }

        public Criteria andUpdaterEqualTo(String value) {
            addCriterion("updater =", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotEqualTo(String value) {
            addCriterion("updater <>", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThan(String value) {
            addCriterion("updater >", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThanOrEqualTo(String value) {
            addCriterion("updater >=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThan(String value) {
            addCriterion("updater <", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThanOrEqualTo(String value) {
            addCriterion("updater <=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLike(String value) {
            addCriterion("updater like", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotLike(String value) {
            addCriterion("updater not like", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterIn(List<String> values) {
            addCriterion("updater in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotIn(List<String> values) {
            addCriterion("updater not in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterBetween(String value1, String value2) {
            addCriterion("updater between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotBetween(String value1, String value2) {
            addCriterion("updater not between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdatedIsNull() {
            addCriterion("updated is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedIsNotNull() {
            addCriterion("updated is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedEqualTo(Date value) {
            addCriterion("updated =", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedNotEqualTo(Date value) {
            addCriterion("updated <>", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedGreaterThan(Date value) {
            addCriterion("updated >", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedGreaterThanOrEqualTo(Date value) {
            addCriterion("updated >=", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedLessThan(Date value) {
            addCriterion("updated <", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedLessThanOrEqualTo(Date value) {
            addCriterion("updated <=", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedIn(List<Date> values) {
            addCriterion("updated in", values, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedNotIn(List<Date> values) {
            addCriterion("updated not in", values, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedBetween(Date value1, Date value2) {
            addCriterion("updated between", value1, value2, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedNotBetween(Date value1, Date value2) {
            addCriterion("updated not between", value1, value2, "updated");
            return (Criteria) this;
        }

        public Criteria andEnableIsNull() {
            addCriterion("enable is null");
            return (Criteria) this;
        }

        public Criteria andEnableIsNotNull() {
            addCriterion("enable is not null");
            return (Criteria) this;
        }

        public Criteria andEnableEqualTo(Boolean value) {
            addCriterion("enable =", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotEqualTo(Boolean value) {
            addCriterion("enable <>", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableGreaterThan(Boolean value) {
            addCriterion("enable >", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableGreaterThanOrEqualTo(Boolean value) {
            addCriterion("enable >=", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableLessThan(Boolean value) {
            addCriterion("enable <", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableLessThanOrEqualTo(Boolean value) {
            addCriterion("enable <=", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableIn(List<Boolean> values) {
            addCriterion("enable in", values, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotIn(List<Boolean> values) {
            addCriterion("enable not in", values, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableBetween(Boolean value1, Boolean value2) {
            addCriterion("enable between", value1, value2, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotBetween(Boolean value1, Boolean value2) {
            addCriterion("enable not between", value1, value2, "enable");
            return (Criteria) this;
        }

        public Criteria andObsDomainIsNull() {
            addCriterion("obs_domain is null");
            return (Criteria) this;
        }

        public Criteria andObsDomainIsNotNull() {
            addCriterion("obs_domain is not null");
            return (Criteria) this;
        }

        public Criteria andObsDomainEqualTo(String value) {
            addCriterion("obs_domain =", value, "obsDomain");
            return (Criteria) this;
        }

        public Criteria andObsDomainNotEqualTo(String value) {
            addCriterion("obs_domain <>", value, "obsDomain");
            return (Criteria) this;
        }

        public Criteria andObsDomainGreaterThan(String value) {
            addCriterion("obs_domain >", value, "obsDomain");
            return (Criteria) this;
        }

        public Criteria andObsDomainGreaterThanOrEqualTo(String value) {
            addCriterion("obs_domain >=", value, "obsDomain");
            return (Criteria) this;
        }

        public Criteria andObsDomainLessThan(String value) {
            addCriterion("obs_domain <", value, "obsDomain");
            return (Criteria) this;
        }

        public Criteria andObsDomainLessThanOrEqualTo(String value) {
            addCriterion("obs_domain <=", value, "obsDomain");
            return (Criteria) this;
        }

        public Criteria andObsDomainLike(String value) {
            addCriterion("obs_domain like", value, "obsDomain");
            return (Criteria) this;
        }

        public Criteria andObsDomainNotLike(String value) {
            addCriterion("obs_domain not like", value, "obsDomain");
            return (Criteria) this;
        }

        public Criteria andObsDomainIn(List<String> values) {
            addCriterion("obs_domain in", values, "obsDomain");
            return (Criteria) this;
        }

        public Criteria andObsDomainNotIn(List<String> values) {
            addCriterion("obs_domain not in", values, "obsDomain");
            return (Criteria) this;
        }

        public Criteria andObsDomainBetween(String value1, String value2) {
            addCriterion("obs_domain between", value1, value2, "obsDomain");
            return (Criteria) this;
        }

        public Criteria andObsDomainNotBetween(String value1, String value2) {
            addCriterion("obs_domain not between", value1, value2, "obsDomain");
            return (Criteria) this;
        }

        public Criteria andObjectUrlIsNull() {
            addCriterion("object_url is null");
            return (Criteria) this;
        }

        public Criteria andObjectUrlIsNotNull() {
            addCriterion("object_url is not null");
            return (Criteria) this;
        }

        public Criteria andObjectUrlEqualTo(String value) {
            addCriterion("object_url =", value, "objectUrl");
            return (Criteria) this;
        }

        public Criteria andObjectUrlNotEqualTo(String value) {
            addCriterion("object_url <>", value, "objectUrl");
            return (Criteria) this;
        }

        public Criteria andObjectUrlGreaterThan(String value) {
            addCriterion("object_url >", value, "objectUrl");
            return (Criteria) this;
        }

        public Criteria andObjectUrlGreaterThanOrEqualTo(String value) {
            addCriterion("object_url >=", value, "objectUrl");
            return (Criteria) this;
        }

        public Criteria andObjectUrlLessThan(String value) {
            addCriterion("object_url <", value, "objectUrl");
            return (Criteria) this;
        }

        public Criteria andObjectUrlLessThanOrEqualTo(String value) {
            addCriterion("object_url <=", value, "objectUrl");
            return (Criteria) this;
        }

        public Criteria andObjectUrlLike(String value) {
            addCriterion("object_url like", value, "objectUrl");
            return (Criteria) this;
        }

        public Criteria andObjectUrlNotLike(String value) {
            addCriterion("object_url not like", value, "objectUrl");
            return (Criteria) this;
        }

        public Criteria andObjectUrlIn(List<String> values) {
            addCriterion("object_url in", values, "objectUrl");
            return (Criteria) this;
        }

        public Criteria andObjectUrlNotIn(List<String> values) {
            addCriterion("object_url not in", values, "objectUrl");
            return (Criteria) this;
        }

        public Criteria andObjectUrlBetween(String value1, String value2) {
            addCriterion("object_url between", value1, value2, "objectUrl");
            return (Criteria) this;
        }

        public Criteria andObjectUrlNotBetween(String value1, String value2) {
            addCriterion("object_url not between", value1, value2, "objectUrl");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table base_obs
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table base_obs
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}