package com.sample.servicecomb.provider.model;

import java.io.Serializable;
import java.util.Date;

public class FaceInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_info.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_info.face_label_id
     *
     * @mbg.generated
     */
    private String faceLabelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_info.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_info.gender
     *
     * @mbg.generated
     */
    private Boolean gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_info.certificate_type
     *
     * @mbg.generated
     */
    private Byte certificateType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_info.certificate_number
     *
     * @mbg.generated
     */
    private String certificateNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_info.birthday
     *
     * @mbg.generated
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_info.position
     *
     * @mbg.generated
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_info.obs_id
     *
     * @mbg.generated
     */
    private Long obsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_info.obs_url
     *
     * @mbg.generated
     */
    private String obsUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_info.province
     *
     * @mbg.generated
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_info.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_info.face_set_id
     *
     * @mbg.generated
     */
    private String faceSetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_info.tel_num
     *
     * @mbg.generated
     */
    private String telNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_info.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_info.created
     *
     * @mbg.generated
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_info.creator
     *
     * @mbg.generated
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_info.updated
     *
     * @mbg.generated
     */
    private Date updated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_info.updator
     *
     * @mbg.generated
     */
    private String updator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table face_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_info.id
     *
     * @return the value of face_info.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_info.id
     *
     * @param id the value for face_info.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_info.face_label_id
     *
     * @return the value of face_info.face_label_id
     *
     * @mbg.generated
     */
    public String getFaceLabelId() {
        return faceLabelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_info.face_label_id
     *
     * @param faceLabelId the value for face_info.face_label_id
     *
     * @mbg.generated
     */
    public void setFaceLabelId(String faceLabelId) {
        this.faceLabelId = faceLabelId == null ? null : faceLabelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_info.name
     *
     * @return the value of face_info.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_info.name
     *
     * @param name the value for face_info.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_info.gender
     *
     * @return the value of face_info.gender
     *
     * @mbg.generated
     */
    public Boolean getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_info.gender
     *
     * @param gender the value for face_info.gender
     *
     * @mbg.generated
     */
    public void setGender(Boolean gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_info.certificate_type
     *
     * @return the value of face_info.certificate_type
     *
     * @mbg.generated
     */
    public Byte getCertificateType() {
        return certificateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_info.certificate_type
     *
     * @param certificateType the value for face_info.certificate_type
     *
     * @mbg.generated
     */
    public void setCertificateType(Byte certificateType) {
        this.certificateType = certificateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_info.certificate_number
     *
     * @return the value of face_info.certificate_number
     *
     * @mbg.generated
     */
    public String getCertificateNumber() {
        return certificateNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_info.certificate_number
     *
     * @param certificateNumber the value for face_info.certificate_number
     *
     * @mbg.generated
     */
    public void setCertificateNumber(String certificateNumber) {
        this.certificateNumber = certificateNumber == null ? null : certificateNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_info.birthday
     *
     * @return the value of face_info.birthday
     *
     * @mbg.generated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_info.birthday
     *
     * @param birthday the value for face_info.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_info.position
     *
     * @return the value of face_info.position
     *
     * @mbg.generated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_info.position
     *
     * @param position the value for face_info.position
     *
     * @mbg.generated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_info.obs_id
     *
     * @return the value of face_info.obs_id
     *
     * @mbg.generated
     */
    public Long getObsId() {
        return obsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_info.obs_id
     *
     * @param obsId the value for face_info.obs_id
     *
     * @mbg.generated
     */
    public void setObsId(Long obsId) {
        this.obsId = obsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_info.obs_url
     *
     * @return the value of face_info.obs_url
     *
     * @mbg.generated
     */
    public String getObsUrl() {
        return obsUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_info.obs_url
     *
     * @param obsUrl the value for face_info.obs_url
     *
     * @mbg.generated
     */
    public void setObsUrl(String obsUrl) {
        this.obsUrl = obsUrl == null ? null : obsUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_info.province
     *
     * @return the value of face_info.province
     *
     * @mbg.generated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_info.province
     *
     * @param province the value for face_info.province
     *
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_info.city
     *
     * @return the value of face_info.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_info.city
     *
     * @param city the value for face_info.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_info.face_set_id
     *
     * @return the value of face_info.face_set_id
     *
     * @mbg.generated
     */
    public String getFaceSetId() {
        return faceSetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_info.face_set_id
     *
     * @param faceSetId the value for face_info.face_set_id
     *
     * @mbg.generated
     */
    public void setFaceSetId(String faceSetId) {
        this.faceSetId = faceSetId == null ? null : faceSetId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_info.tel_num
     *
     * @return the value of face_info.tel_num
     *
     * @mbg.generated
     */
    public String getTelNum() {
        return telNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_info.tel_num
     *
     * @param telNum the value for face_info.tel_num
     *
     * @mbg.generated
     */
    public void setTelNum(String telNum) {
        this.telNum = telNum == null ? null : telNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_info.description
     *
     * @return the value of face_info.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_info.description
     *
     * @param description the value for face_info.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_info.created
     *
     * @return the value of face_info.created
     *
     * @mbg.generated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_info.created
     *
     * @param created the value for face_info.created
     *
     * @mbg.generated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_info.creator
     *
     * @return the value of face_info.creator
     *
     * @mbg.generated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_info.creator
     *
     * @param creator the value for face_info.creator
     *
     * @mbg.generated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_info.updated
     *
     * @return the value of face_info.updated
     *
     * @mbg.generated
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_info.updated
     *
     * @param updated the value for face_info.updated
     *
     * @mbg.generated
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_info.updator
     *
     * @return the value of face_info.updator
     *
     * @mbg.generated
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_info.updator
     *
     * @param updator the value for face_info.updator
     *
     * @mbg.generated
     */
    public void setUpdator(String updator) {
        this.updator = updator == null ? null : updator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_info
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FaceInfo other = (FaceInfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getFaceLabelId() == null ? other.getFaceLabelId() == null : this.getFaceLabelId().equals(other.getFaceLabelId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getGender() == null ? other.getGender() == null : this.getGender().equals(other.getGender()))
            && (this.getCertificateType() == null ? other.getCertificateType() == null : this.getCertificateType().equals(other.getCertificateType()))
            && (this.getCertificateNumber() == null ? other.getCertificateNumber() == null : this.getCertificateNumber().equals(other.getCertificateNumber()))
            && (this.getBirthday() == null ? other.getBirthday() == null : this.getBirthday().equals(other.getBirthday()))
            && (this.getPosition() == null ? other.getPosition() == null : this.getPosition().equals(other.getPosition()))
            && (this.getObsId() == null ? other.getObsId() == null : this.getObsId().equals(other.getObsId()))
            && (this.getObsUrl() == null ? other.getObsUrl() == null : this.getObsUrl().equals(other.getObsUrl()))
            && (this.getProvince() == null ? other.getProvince() == null : this.getProvince().equals(other.getProvince()))
            && (this.getCity() == null ? other.getCity() == null : this.getCity().equals(other.getCity()))
            && (this.getFaceSetId() == null ? other.getFaceSetId() == null : this.getFaceSetId().equals(other.getFaceSetId()))
            && (this.getTelNum() == null ? other.getTelNum() == null : this.getTelNum().equals(other.getTelNum()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getCreated() == null ? other.getCreated() == null : this.getCreated().equals(other.getCreated()))
            && (this.getCreator() == null ? other.getCreator() == null : this.getCreator().equals(other.getCreator()))
            && (this.getUpdated() == null ? other.getUpdated() == null : this.getUpdated().equals(other.getUpdated()))
            && (this.getUpdator() == null ? other.getUpdator() == null : this.getUpdator().equals(other.getUpdator()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_info
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getFaceLabelId() == null) ? 0 : getFaceLabelId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getGender() == null) ? 0 : getGender().hashCode());
        result = prime * result + ((getCertificateType() == null) ? 0 : getCertificateType().hashCode());
        result = prime * result + ((getCertificateNumber() == null) ? 0 : getCertificateNumber().hashCode());
        result = prime * result + ((getBirthday() == null) ? 0 : getBirthday().hashCode());
        result = prime * result + ((getPosition() == null) ? 0 : getPosition().hashCode());
        result = prime * result + ((getObsId() == null) ? 0 : getObsId().hashCode());
        result = prime * result + ((getObsUrl() == null) ? 0 : getObsUrl().hashCode());
        result = prime * result + ((getProvince() == null) ? 0 : getProvince().hashCode());
        result = prime * result + ((getCity() == null) ? 0 : getCity().hashCode());
        result = prime * result + ((getFaceSetId() == null) ? 0 : getFaceSetId().hashCode());
        result = prime * result + ((getTelNum() == null) ? 0 : getTelNum().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getCreated() == null) ? 0 : getCreated().hashCode());
        result = prime * result + ((getCreator() == null) ? 0 : getCreator().hashCode());
        result = prime * result + ((getUpdated() == null) ? 0 : getUpdated().hashCode());
        result = prime * result + ((getUpdator() == null) ? 0 : getUpdator().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", faceLabelId=").append(faceLabelId);
        sb.append(", name=").append(name);
        sb.append(", gender=").append(gender);
        sb.append(", certificateType=").append(certificateType);
        sb.append(", certificateNumber=").append(certificateNumber);
        sb.append(", birthday=").append(birthday);
        sb.append(", position=").append(position);
        sb.append(", obsId=").append(obsId);
        sb.append(", obsUrl=").append(obsUrl);
        sb.append(", province=").append(province);
        sb.append(", city=").append(city);
        sb.append(", faceSetId=").append(faceSetId);
        sb.append(", telNum=").append(telNum);
        sb.append(", description=").append(description);
        sb.append(", created=").append(created);
        sb.append(", creator=").append(creator);
        sb.append(", updated=").append(updated);
        sb.append(", updator=").append(updator);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}