package com.sample.servicecomb.provider.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FaceHisExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table face_his
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table face_his
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table face_his
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_his
     *
     * @mbg.generated
     */
    public FaceHisExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_his
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_his
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_his
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_his
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_his
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_his
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_his
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_his
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_his
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_his
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table face_his
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andFaceSetIdIsNull() {
            addCriterion("face_set_id is null");
            return (Criteria) this;
        }

        public Criteria andFaceSetIdIsNotNull() {
            addCriterion("face_set_id is not null");
            return (Criteria) this;
        }

        public Criteria andFaceSetIdEqualTo(String value) {
            addCriterion("face_set_id =", value, "faceSetId");
            return (Criteria) this;
        }

        public Criteria andFaceSetIdNotEqualTo(String value) {
            addCriterion("face_set_id <>", value, "faceSetId");
            return (Criteria) this;
        }

        public Criteria andFaceSetIdGreaterThan(String value) {
            addCriterion("face_set_id >", value, "faceSetId");
            return (Criteria) this;
        }

        public Criteria andFaceSetIdGreaterThanOrEqualTo(String value) {
            addCriterion("face_set_id >=", value, "faceSetId");
            return (Criteria) this;
        }

        public Criteria andFaceSetIdLessThan(String value) {
            addCriterion("face_set_id <", value, "faceSetId");
            return (Criteria) this;
        }

        public Criteria andFaceSetIdLessThanOrEqualTo(String value) {
            addCriterion("face_set_id <=", value, "faceSetId");
            return (Criteria) this;
        }

        public Criteria andFaceSetIdLike(String value) {
            addCriterion("face_set_id like", value, "faceSetId");
            return (Criteria) this;
        }

        public Criteria andFaceSetIdNotLike(String value) {
            addCriterion("face_set_id not like", value, "faceSetId");
            return (Criteria) this;
        }

        public Criteria andFaceSetIdIn(List<String> values) {
            addCriterion("face_set_id in", values, "faceSetId");
            return (Criteria) this;
        }

        public Criteria andFaceSetIdNotIn(List<String> values) {
            addCriterion("face_set_id not in", values, "faceSetId");
            return (Criteria) this;
        }

        public Criteria andFaceSetIdBetween(String value1, String value2) {
            addCriterion("face_set_id between", value1, value2, "faceSetId");
            return (Criteria) this;
        }

        public Criteria andFaceSetIdNotBetween(String value1, String value2) {
            addCriterion("face_set_id not between", value1, value2, "faceSetId");
            return (Criteria) this;
        }

        public Criteria andFaceLabelIdIsNull() {
            addCriterion("face_label_id is null");
            return (Criteria) this;
        }

        public Criteria andFaceLabelIdIsNotNull() {
            addCriterion("face_label_id is not null");
            return (Criteria) this;
        }

        public Criteria andFaceLabelIdEqualTo(String value) {
            addCriterion("face_label_id =", value, "faceLabelId");
            return (Criteria) this;
        }

        public Criteria andFaceLabelIdNotEqualTo(String value) {
            addCriterion("face_label_id <>", value, "faceLabelId");
            return (Criteria) this;
        }

        public Criteria andFaceLabelIdGreaterThan(String value) {
            addCriterion("face_label_id >", value, "faceLabelId");
            return (Criteria) this;
        }

        public Criteria andFaceLabelIdGreaterThanOrEqualTo(String value) {
            addCriterion("face_label_id >=", value, "faceLabelId");
            return (Criteria) this;
        }

        public Criteria andFaceLabelIdLessThan(String value) {
            addCriterion("face_label_id <", value, "faceLabelId");
            return (Criteria) this;
        }

        public Criteria andFaceLabelIdLessThanOrEqualTo(String value) {
            addCriterion("face_label_id <=", value, "faceLabelId");
            return (Criteria) this;
        }

        public Criteria andFaceLabelIdLike(String value) {
            addCriterion("face_label_id like", value, "faceLabelId");
            return (Criteria) this;
        }

        public Criteria andFaceLabelIdNotLike(String value) {
            addCriterion("face_label_id not like", value, "faceLabelId");
            return (Criteria) this;
        }

        public Criteria andFaceLabelIdIn(List<String> values) {
            addCriterion("face_label_id in", values, "faceLabelId");
            return (Criteria) this;
        }

        public Criteria andFaceLabelIdNotIn(List<String> values) {
            addCriterion("face_label_id not in", values, "faceLabelId");
            return (Criteria) this;
        }

        public Criteria andFaceLabelIdBetween(String value1, String value2) {
            addCriterion("face_label_id between", value1, value2, "faceLabelId");
            return (Criteria) this;
        }

        public Criteria andFaceLabelIdNotBetween(String value1, String value2) {
            addCriterion("face_label_id not between", value1, value2, "faceLabelId");
            return (Criteria) this;
        }

        public Criteria andSmallObsUrlIsNull() {
            addCriterion("small_obs_url is null");
            return (Criteria) this;
        }

        public Criteria andSmallObsUrlIsNotNull() {
            addCriterion("small_obs_url is not null");
            return (Criteria) this;
        }

        public Criteria andSmallObsUrlEqualTo(String value) {
            addCriterion("small_obs_url =", value, "smallObsUrl");
            return (Criteria) this;
        }

        public Criteria andSmallObsUrlNotEqualTo(String value) {
            addCriterion("small_obs_url <>", value, "smallObsUrl");
            return (Criteria) this;
        }

        public Criteria andSmallObsUrlGreaterThan(String value) {
            addCriterion("small_obs_url >", value, "smallObsUrl");
            return (Criteria) this;
        }

        public Criteria andSmallObsUrlGreaterThanOrEqualTo(String value) {
            addCriterion("small_obs_url >=", value, "smallObsUrl");
            return (Criteria) this;
        }

        public Criteria andSmallObsUrlLessThan(String value) {
            addCriterion("small_obs_url <", value, "smallObsUrl");
            return (Criteria) this;
        }

        public Criteria andSmallObsUrlLessThanOrEqualTo(String value) {
            addCriterion("small_obs_url <=", value, "smallObsUrl");
            return (Criteria) this;
        }

        public Criteria andSmallObsUrlLike(String value) {
            addCriterion("small_obs_url like", value, "smallObsUrl");
            return (Criteria) this;
        }

        public Criteria andSmallObsUrlNotLike(String value) {
            addCriterion("small_obs_url not like", value, "smallObsUrl");
            return (Criteria) this;
        }

        public Criteria andSmallObsUrlIn(List<String> values) {
            addCriterion("small_obs_url in", values, "smallObsUrl");
            return (Criteria) this;
        }

        public Criteria andSmallObsUrlNotIn(List<String> values) {
            addCriterion("small_obs_url not in", values, "smallObsUrl");
            return (Criteria) this;
        }

        public Criteria andSmallObsUrlBetween(String value1, String value2) {
            addCriterion("small_obs_url between", value1, value2, "smallObsUrl");
            return (Criteria) this;
        }

        public Criteria andSmallObsUrlNotBetween(String value1, String value2) {
            addCriterion("small_obs_url not between", value1, value2, "smallObsUrl");
            return (Criteria) this;
        }

        public Criteria andSimilarityIsNull() {
            addCriterion("similarity is null");
            return (Criteria) this;
        }

        public Criteria andSimilarityIsNotNull() {
            addCriterion("similarity is not null");
            return (Criteria) this;
        }

        public Criteria andSimilarityEqualTo(Double value) {
            addCriterion("similarity =", value, "similarity");
            return (Criteria) this;
        }

        public Criteria andSimilarityNotEqualTo(Double value) {
            addCriterion("similarity <>", value, "similarity");
            return (Criteria) this;
        }

        public Criteria andSimilarityGreaterThan(Double value) {
            addCriterion("similarity >", value, "similarity");
            return (Criteria) this;
        }

        public Criteria andSimilarityGreaterThanOrEqualTo(Double value) {
            addCriterion("similarity >=", value, "similarity");
            return (Criteria) this;
        }

        public Criteria andSimilarityLessThan(Double value) {
            addCriterion("similarity <", value, "similarity");
            return (Criteria) this;
        }

        public Criteria andSimilarityLessThanOrEqualTo(Double value) {
            addCriterion("similarity <=", value, "similarity");
            return (Criteria) this;
        }

        public Criteria andSimilarityIn(List<Double> values) {
            addCriterion("similarity in", values, "similarity");
            return (Criteria) this;
        }

        public Criteria andSimilarityNotIn(List<Double> values) {
            addCriterion("similarity not in", values, "similarity");
            return (Criteria) this;
        }

        public Criteria andSimilarityBetween(Double value1, Double value2) {
            addCriterion("similarity between", value1, value2, "similarity");
            return (Criteria) this;
        }

        public Criteria andSimilarityNotBetween(Double value1, Double value2) {
            addCriterion("similarity not between", value1, value2, "similarity");
            return (Criteria) this;
        }

        public Criteria andFaceDateIsNull() {
            addCriterion("face_date is null");
            return (Criteria) this;
        }

        public Criteria andFaceDateIsNotNull() {
            addCriterion("face_date is not null");
            return (Criteria) this;
        }

        public Criteria andFaceDateEqualTo(Date value) {
            addCriterion("face_date =", value, "faceDate");
            return (Criteria) this;
        }

        public Criteria andFaceDateNotEqualTo(Date value) {
            addCriterion("face_date <>", value, "faceDate");
            return (Criteria) this;
        }

        public Criteria andFaceDateGreaterThan(Date value) {
            addCriterion("face_date >", value, "faceDate");
            return (Criteria) this;
        }

        public Criteria andFaceDateGreaterThanOrEqualTo(Date value) {
            addCriterion("face_date >=", value, "faceDate");
            return (Criteria) this;
        }

        public Criteria andFaceDateLessThan(Date value) {
            addCriterion("face_date <", value, "faceDate");
            return (Criteria) this;
        }

        public Criteria andFaceDateLessThanOrEqualTo(Date value) {
            addCriterion("face_date <=", value, "faceDate");
            return (Criteria) this;
        }

        public Criteria andFaceDateIn(List<Date> values) {
            addCriterion("face_date in", values, "faceDate");
            return (Criteria) this;
        }

        public Criteria andFaceDateNotIn(List<Date> values) {
            addCriterion("face_date not in", values, "faceDate");
            return (Criteria) this;
        }

        public Criteria andFaceDateBetween(Date value1, Date value2) {
            addCriterion("face_date between", value1, value2, "faceDate");
            return (Criteria) this;
        }

        public Criteria andFaceDateNotBetween(Date value1, Date value2) {
            addCriterion("face_date not between", value1, value2, "faceDate");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andAgeIsNull() {
            addCriterion("age is null");
            return (Criteria) this;
        }

        public Criteria andAgeIsNotNull() {
            addCriterion("age is not null");
            return (Criteria) this;
        }

        public Criteria andAgeEqualTo(Integer value) {
            addCriterion("age =", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotEqualTo(Integer value) {
            addCriterion("age <>", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThan(Integer value) {
            addCriterion("age >", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("age >=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThan(Integer value) {
            addCriterion("age <", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThanOrEqualTo(Integer value) {
            addCriterion("age <=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeIn(List<Integer> values) {
            addCriterion("age in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotIn(List<Integer> values) {
            addCriterion("age not in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeBetween(Integer value1, Integer value2) {
            addCriterion("age between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotBetween(Integer value1, Integer value2) {
            addCriterion("age not between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andGenderIsNull() {
            addCriterion("gender is null");
            return (Criteria) this;
        }

        public Criteria andGenderIsNotNull() {
            addCriterion("gender is not null");
            return (Criteria) this;
        }

        public Criteria andGenderEqualTo(String value) {
            addCriterion("gender =", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotEqualTo(String value) {
            addCriterion("gender <>", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThan(String value) {
            addCriterion("gender >", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThanOrEqualTo(String value) {
            addCriterion("gender >=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThan(String value) {
            addCriterion("gender <", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThanOrEqualTo(String value) {
            addCriterion("gender <=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLike(String value) {
            addCriterion("gender like", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotLike(String value) {
            addCriterion("gender not like", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderIn(List<String> values) {
            addCriterion("gender in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotIn(List<String> values) {
            addCriterion("gender not in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderBetween(String value1, String value2) {
            addCriterion("gender between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotBetween(String value1, String value2) {
            addCriterion("gender not between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andHatIsNull() {
            addCriterion("hat is null");
            return (Criteria) this;
        }

        public Criteria andHatIsNotNull() {
            addCriterion("hat is not null");
            return (Criteria) this;
        }

        public Criteria andHatEqualTo(String value) {
            addCriterion("hat =", value, "hat");
            return (Criteria) this;
        }

        public Criteria andHatNotEqualTo(String value) {
            addCriterion("hat <>", value, "hat");
            return (Criteria) this;
        }

        public Criteria andHatGreaterThan(String value) {
            addCriterion("hat >", value, "hat");
            return (Criteria) this;
        }

        public Criteria andHatGreaterThanOrEqualTo(String value) {
            addCriterion("hat >=", value, "hat");
            return (Criteria) this;
        }

        public Criteria andHatLessThan(String value) {
            addCriterion("hat <", value, "hat");
            return (Criteria) this;
        }

        public Criteria andHatLessThanOrEqualTo(String value) {
            addCriterion("hat <=", value, "hat");
            return (Criteria) this;
        }

        public Criteria andHatLike(String value) {
            addCriterion("hat like", value, "hat");
            return (Criteria) this;
        }

        public Criteria andHatNotLike(String value) {
            addCriterion("hat not like", value, "hat");
            return (Criteria) this;
        }

        public Criteria andHatIn(List<String> values) {
            addCriterion("hat in", values, "hat");
            return (Criteria) this;
        }

        public Criteria andHatNotIn(List<String> values) {
            addCriterion("hat not in", values, "hat");
            return (Criteria) this;
        }

        public Criteria andHatBetween(String value1, String value2) {
            addCriterion("hat between", value1, value2, "hat");
            return (Criteria) this;
        }

        public Criteria andHatNotBetween(String value1, String value2) {
            addCriterion("hat not between", value1, value2, "hat");
            return (Criteria) this;
        }

        public Criteria andSmileIsNull() {
            addCriterion("smile is null");
            return (Criteria) this;
        }

        public Criteria andSmileIsNotNull() {
            addCriterion("smile is not null");
            return (Criteria) this;
        }

        public Criteria andSmileEqualTo(String value) {
            addCriterion("smile =", value, "smile");
            return (Criteria) this;
        }

        public Criteria andSmileNotEqualTo(String value) {
            addCriterion("smile <>", value, "smile");
            return (Criteria) this;
        }

        public Criteria andSmileGreaterThan(String value) {
            addCriterion("smile >", value, "smile");
            return (Criteria) this;
        }

        public Criteria andSmileGreaterThanOrEqualTo(String value) {
            addCriterion("smile >=", value, "smile");
            return (Criteria) this;
        }

        public Criteria andSmileLessThan(String value) {
            addCriterion("smile <", value, "smile");
            return (Criteria) this;
        }

        public Criteria andSmileLessThanOrEqualTo(String value) {
            addCriterion("smile <=", value, "smile");
            return (Criteria) this;
        }

        public Criteria andSmileLike(String value) {
            addCriterion("smile like", value, "smile");
            return (Criteria) this;
        }

        public Criteria andSmileNotLike(String value) {
            addCriterion("smile not like", value, "smile");
            return (Criteria) this;
        }

        public Criteria andSmileIn(List<String> values) {
            addCriterion("smile in", values, "smile");
            return (Criteria) this;
        }

        public Criteria andSmileNotIn(List<String> values) {
            addCriterion("smile not in", values, "smile");
            return (Criteria) this;
        }

        public Criteria andSmileBetween(String value1, String value2) {
            addCriterion("smile between", value1, value2, "smile");
            return (Criteria) this;
        }

        public Criteria andSmileNotBetween(String value1, String value2) {
            addCriterion("smile not between", value1, value2, "smile");
            return (Criteria) this;
        }

        public Criteria andGlassIsNull() {
            addCriterion("glass is null");
            return (Criteria) this;
        }

        public Criteria andGlassIsNotNull() {
            addCriterion("glass is not null");
            return (Criteria) this;
        }

        public Criteria andGlassEqualTo(String value) {
            addCriterion("glass =", value, "glass");
            return (Criteria) this;
        }

        public Criteria andGlassNotEqualTo(String value) {
            addCriterion("glass <>", value, "glass");
            return (Criteria) this;
        }

        public Criteria andGlassGreaterThan(String value) {
            addCriterion("glass >", value, "glass");
            return (Criteria) this;
        }

        public Criteria andGlassGreaterThanOrEqualTo(String value) {
            addCriterion("glass >=", value, "glass");
            return (Criteria) this;
        }

        public Criteria andGlassLessThan(String value) {
            addCriterion("glass <", value, "glass");
            return (Criteria) this;
        }

        public Criteria andGlassLessThanOrEqualTo(String value) {
            addCriterion("glass <=", value, "glass");
            return (Criteria) this;
        }

        public Criteria andGlassLike(String value) {
            addCriterion("glass like", value, "glass");
            return (Criteria) this;
        }

        public Criteria andGlassNotLike(String value) {
            addCriterion("glass not like", value, "glass");
            return (Criteria) this;
        }

        public Criteria andGlassIn(List<String> values) {
            addCriterion("glass in", values, "glass");
            return (Criteria) this;
        }

        public Criteria andGlassNotIn(List<String> values) {
            addCriterion("glass not in", values, "glass");
            return (Criteria) this;
        }

        public Criteria andGlassBetween(String value1, String value2) {
            addCriterion("glass between", value1, value2, "glass");
            return (Criteria) this;
        }

        public Criteria andGlassNotBetween(String value1, String value2) {
            addCriterion("glass not between", value1, value2, "glass");
            return (Criteria) this;
        }

        public Criteria andCameraIdIsNull() {
            addCriterion("camera_id is null");
            return (Criteria) this;
        }

        public Criteria andCameraIdIsNotNull() {
            addCriterion("camera_id is not null");
            return (Criteria) this;
        }

        public Criteria andCameraIdEqualTo(String value) {
            addCriterion("camera_id =", value, "cameraId");
            return (Criteria) this;
        }

        public Criteria andCameraIdNotEqualTo(String value) {
            addCriterion("camera_id <>", value, "cameraId");
            return (Criteria) this;
        }

        public Criteria andCameraIdGreaterThan(String value) {
            addCriterion("camera_id >", value, "cameraId");
            return (Criteria) this;
        }

        public Criteria andCameraIdGreaterThanOrEqualTo(String value) {
            addCriterion("camera_id >=", value, "cameraId");
            return (Criteria) this;
        }

        public Criteria andCameraIdLessThan(String value) {
            addCriterion("camera_id <", value, "cameraId");
            return (Criteria) this;
        }

        public Criteria andCameraIdLessThanOrEqualTo(String value) {
            addCriterion("camera_id <=", value, "cameraId");
            return (Criteria) this;
        }

        public Criteria andCameraIdLike(String value) {
            addCriterion("camera_id like", value, "cameraId");
            return (Criteria) this;
        }

        public Criteria andCameraIdNotLike(String value) {
            addCriterion("camera_id not like", value, "cameraId");
            return (Criteria) this;
        }

        public Criteria andCameraIdIn(List<String> values) {
            addCriterion("camera_id in", values, "cameraId");
            return (Criteria) this;
        }

        public Criteria andCameraIdNotIn(List<String> values) {
            addCriterion("camera_id not in", values, "cameraId");
            return (Criteria) this;
        }

        public Criteria andCameraIdBetween(String value1, String value2) {
            addCriterion("camera_id between", value1, value2, "cameraId");
            return (Criteria) this;
        }

        public Criteria andCameraIdNotBetween(String value1, String value2) {
            addCriterion("camera_id not between", value1, value2, "cameraId");
            return (Criteria) this;
        }

        public Criteria andOriImgIdIsNull() {
            addCriterion("ori_img_id is null");
            return (Criteria) this;
        }

        public Criteria andOriImgIdIsNotNull() {
            addCriterion("ori_img_id is not null");
            return (Criteria) this;
        }

        public Criteria andOriImgIdEqualTo(String value) {
            addCriterion("ori_img_id =", value, "oriImgId");
            return (Criteria) this;
        }

        public Criteria andOriImgIdNotEqualTo(String value) {
            addCriterion("ori_img_id <>", value, "oriImgId");
            return (Criteria) this;
        }

        public Criteria andOriImgIdGreaterThan(String value) {
            addCriterion("ori_img_id >", value, "oriImgId");
            return (Criteria) this;
        }

        public Criteria andOriImgIdGreaterThanOrEqualTo(String value) {
            addCriterion("ori_img_id >=", value, "oriImgId");
            return (Criteria) this;
        }

        public Criteria andOriImgIdLessThan(String value) {
            addCriterion("ori_img_id <", value, "oriImgId");
            return (Criteria) this;
        }

        public Criteria andOriImgIdLessThanOrEqualTo(String value) {
            addCriterion("ori_img_id <=", value, "oriImgId");
            return (Criteria) this;
        }

        public Criteria andOriImgIdLike(String value) {
            addCriterion("ori_img_id like", value, "oriImgId");
            return (Criteria) this;
        }

        public Criteria andOriImgIdNotLike(String value) {
            addCriterion("ori_img_id not like", value, "oriImgId");
            return (Criteria) this;
        }

        public Criteria andOriImgIdIn(List<String> values) {
            addCriterion("ori_img_id in", values, "oriImgId");
            return (Criteria) this;
        }

        public Criteria andOriImgIdNotIn(List<String> values) {
            addCriterion("ori_img_id not in", values, "oriImgId");
            return (Criteria) this;
        }

        public Criteria andOriImgIdBetween(String value1, String value2) {
            addCriterion("ori_img_id between", value1, value2, "oriImgId");
            return (Criteria) this;
        }

        public Criteria andOriImgIdNotBetween(String value1, String value2) {
            addCriterion("ori_img_id not between", value1, value2, "oriImgId");
            return (Criteria) this;
        }

        public Criteria andOriginalObsUrlIsNull() {
            addCriterion("original_obs_url is null");
            return (Criteria) this;
        }

        public Criteria andOriginalObsUrlIsNotNull() {
            addCriterion("original_obs_url is not null");
            return (Criteria) this;
        }

        public Criteria andOriginalObsUrlEqualTo(String value) {
            addCriterion("original_obs_url =", value, "originalObsUrl");
            return (Criteria) this;
        }

        public Criteria andOriginalObsUrlNotEqualTo(String value) {
            addCriterion("original_obs_url <>", value, "originalObsUrl");
            return (Criteria) this;
        }

        public Criteria andOriginalObsUrlGreaterThan(String value) {
            addCriterion("original_obs_url >", value, "originalObsUrl");
            return (Criteria) this;
        }

        public Criteria andOriginalObsUrlGreaterThanOrEqualTo(String value) {
            addCriterion("original_obs_url >=", value, "originalObsUrl");
            return (Criteria) this;
        }

        public Criteria andOriginalObsUrlLessThan(String value) {
            addCriterion("original_obs_url <", value, "originalObsUrl");
            return (Criteria) this;
        }

        public Criteria andOriginalObsUrlLessThanOrEqualTo(String value) {
            addCriterion("original_obs_url <=", value, "originalObsUrl");
            return (Criteria) this;
        }

        public Criteria andOriginalObsUrlLike(String value) {
            addCriterion("original_obs_url like", value, "originalObsUrl");
            return (Criteria) this;
        }

        public Criteria andOriginalObsUrlNotLike(String value) {
            addCriterion("original_obs_url not like", value, "originalObsUrl");
            return (Criteria) this;
        }

        public Criteria andOriginalObsUrlIn(List<String> values) {
            addCriterion("original_obs_url in", values, "originalObsUrl");
            return (Criteria) this;
        }

        public Criteria andOriginalObsUrlNotIn(List<String> values) {
            addCriterion("original_obs_url not in", values, "originalObsUrl");
            return (Criteria) this;
        }

        public Criteria andOriginalObsUrlBetween(String value1, String value2) {
            addCriterion("original_obs_url between", value1, value2, "originalObsUrl");
            return (Criteria) this;
        }

        public Criteria andOriginalObsUrlNotBetween(String value1, String value2) {
            addCriterion("original_obs_url not between", value1, value2, "originalObsUrl");
            return (Criteria) this;
        }

        public Criteria andOriFaceLabelIdIsNull() {
            addCriterion("ori_face_label_id is null");
            return (Criteria) this;
        }

        public Criteria andOriFaceLabelIdIsNotNull() {
            addCriterion("ori_face_label_id is not null");
            return (Criteria) this;
        }

        public Criteria andOriFaceLabelIdEqualTo(String value) {
            addCriterion("ori_face_label_id =", value, "oriFaceLabelId");
            return (Criteria) this;
        }

        public Criteria andOriFaceLabelIdNotEqualTo(String value) {
            addCriterion("ori_face_label_id <>", value, "oriFaceLabelId");
            return (Criteria) this;
        }

        public Criteria andOriFaceLabelIdGreaterThan(String value) {
            addCriterion("ori_face_label_id >", value, "oriFaceLabelId");
            return (Criteria) this;
        }

        public Criteria andOriFaceLabelIdGreaterThanOrEqualTo(String value) {
            addCriterion("ori_face_label_id >=", value, "oriFaceLabelId");
            return (Criteria) this;
        }

        public Criteria andOriFaceLabelIdLessThan(String value) {
            addCriterion("ori_face_label_id <", value, "oriFaceLabelId");
            return (Criteria) this;
        }

        public Criteria andOriFaceLabelIdLessThanOrEqualTo(String value) {
            addCriterion("ori_face_label_id <=", value, "oriFaceLabelId");
            return (Criteria) this;
        }

        public Criteria andOriFaceLabelIdLike(String value) {
            addCriterion("ori_face_label_id like", value, "oriFaceLabelId");
            return (Criteria) this;
        }

        public Criteria andOriFaceLabelIdNotLike(String value) {
            addCriterion("ori_face_label_id not like", value, "oriFaceLabelId");
            return (Criteria) this;
        }

        public Criteria andOriFaceLabelIdIn(List<String> values) {
            addCriterion("ori_face_label_id in", values, "oriFaceLabelId");
            return (Criteria) this;
        }

        public Criteria andOriFaceLabelIdNotIn(List<String> values) {
            addCriterion("ori_face_label_id not in", values, "oriFaceLabelId");
            return (Criteria) this;
        }

        public Criteria andOriFaceLabelIdBetween(String value1, String value2) {
            addCriterion("ori_face_label_id between", value1, value2, "oriFaceLabelId");
            return (Criteria) this;
        }

        public Criteria andOriFaceLabelIdNotBetween(String value1, String value2) {
            addCriterion("ori_face_label_id not between", value1, value2, "oriFaceLabelId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table face_his
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table face_his
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}