package com.sample.servicecomb.provider.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FaceSetExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table face_set
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table face_set
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table face_set
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_set
     *
     * @mbg.generated
     */
    public FaceSetExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_set
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_set
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_set
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_set
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_set
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_set
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_set
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_set
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_set
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_set
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table face_set
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andFaceSetNameIsNull() {
            addCriterion("face_set_name is null");
            return (Criteria) this;
        }

        public Criteria andFaceSetNameIsNotNull() {
            addCriterion("face_set_name is not null");
            return (Criteria) this;
        }

        public Criteria andFaceSetNameEqualTo(String value) {
            addCriterion("face_set_name =", value, "faceSetName");
            return (Criteria) this;
        }

        public Criteria andFaceSetNameNotEqualTo(String value) {
            addCriterion("face_set_name <>", value, "faceSetName");
            return (Criteria) this;
        }

        public Criteria andFaceSetNameGreaterThan(String value) {
            addCriterion("face_set_name >", value, "faceSetName");
            return (Criteria) this;
        }

        public Criteria andFaceSetNameGreaterThanOrEqualTo(String value) {
            addCriterion("face_set_name >=", value, "faceSetName");
            return (Criteria) this;
        }

        public Criteria andFaceSetNameLessThan(String value) {
            addCriterion("face_set_name <", value, "faceSetName");
            return (Criteria) this;
        }

        public Criteria andFaceSetNameLessThanOrEqualTo(String value) {
            addCriterion("face_set_name <=", value, "faceSetName");
            return (Criteria) this;
        }

        public Criteria andFaceSetNameLike(String value) {
            addCriterion("face_set_name like", value, "faceSetName");
            return (Criteria) this;
        }

        public Criteria andFaceSetNameNotLike(String value) {
            addCriterion("face_set_name not like", value, "faceSetName");
            return (Criteria) this;
        }

        public Criteria andFaceSetNameIn(List<String> values) {
            addCriterion("face_set_name in", values, "faceSetName");
            return (Criteria) this;
        }

        public Criteria andFaceSetNameNotIn(List<String> values) {
            addCriterion("face_set_name not in", values, "faceSetName");
            return (Criteria) this;
        }

        public Criteria andFaceSetNameBetween(String value1, String value2) {
            addCriterion("face_set_name between", value1, value2, "faceSetName");
            return (Criteria) this;
        }

        public Criteria andFaceSetNameNotBetween(String value1, String value2) {
            addCriterion("face_set_name not between", value1, value2, "faceSetName");
            return (Criteria) this;
        }

        public Criteria andFaceSetIdIsNull() {
            addCriterion("face_set_id is null");
            return (Criteria) this;
        }

        public Criteria andFaceSetIdIsNotNull() {
            addCriterion("face_set_id is not null");
            return (Criteria) this;
        }

        public Criteria andFaceSetIdEqualTo(String value) {
            addCriterion("face_set_id =", value, "faceSetId");
            return (Criteria) this;
        }

        public Criteria andFaceSetIdNotEqualTo(String value) {
            addCriterion("face_set_id <>", value, "faceSetId");
            return (Criteria) this;
        }

        public Criteria andFaceSetIdGreaterThan(String value) {
            addCriterion("face_set_id >", value, "faceSetId");
            return (Criteria) this;
        }

        public Criteria andFaceSetIdGreaterThanOrEqualTo(String value) {
            addCriterion("face_set_id >=", value, "faceSetId");
            return (Criteria) this;
        }

        public Criteria andFaceSetIdLessThan(String value) {
            addCriterion("face_set_id <", value, "faceSetId");
            return (Criteria) this;
        }

        public Criteria andFaceSetIdLessThanOrEqualTo(String value) {
            addCriterion("face_set_id <=", value, "faceSetId");
            return (Criteria) this;
        }

        public Criteria andFaceSetIdLike(String value) {
            addCriterion("face_set_id like", value, "faceSetId");
            return (Criteria) this;
        }

        public Criteria andFaceSetIdNotLike(String value) {
            addCriterion("face_set_id not like", value, "faceSetId");
            return (Criteria) this;
        }

        public Criteria andFaceSetIdIn(List<String> values) {
            addCriterion("face_set_id in", values, "faceSetId");
            return (Criteria) this;
        }

        public Criteria andFaceSetIdNotIn(List<String> values) {
            addCriterion("face_set_id not in", values, "faceSetId");
            return (Criteria) this;
        }

        public Criteria andFaceSetIdBetween(String value1, String value2) {
            addCriterion("face_set_id between", value1, value2, "faceSetId");
            return (Criteria) this;
        }

        public Criteria andFaceSetIdNotBetween(String value1, String value2) {
            addCriterion("face_set_id not between", value1, value2, "faceSetId");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("creator is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("creator is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("creator =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("creator <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("creator >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("creator >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("creator <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("creator <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("creator like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("creator not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("creator in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("creator not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("creator between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("creator not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNull() {
            addCriterion("created is null");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNotNull() {
            addCriterion("created is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedEqualTo(Date value) {
            addCriterion("created =", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotEqualTo(Date value) {
            addCriterion("created <>", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThan(Date value) {
            addCriterion("created >", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("created >=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThan(Date value) {
            addCriterion("created <", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThanOrEqualTo(Date value) {
            addCriterion("created <=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedIn(List<Date> values) {
            addCriterion("created in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotIn(List<Date> values) {
            addCriterion("created not in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedBetween(Date value1, Date value2) {
            addCriterion("created between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotBetween(Date value1, Date value2) {
            addCriterion("created not between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andUpdatorIsNull() {
            addCriterion("updator is null");
            return (Criteria) this;
        }

        public Criteria andUpdatorIsNotNull() {
            addCriterion("updator is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatorEqualTo(String value) {
            addCriterion("updator =", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorNotEqualTo(String value) {
            addCriterion("updator <>", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorGreaterThan(String value) {
            addCriterion("updator >", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorGreaterThanOrEqualTo(String value) {
            addCriterion("updator >=", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorLessThan(String value) {
            addCriterion("updator <", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorLessThanOrEqualTo(String value) {
            addCriterion("updator <=", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorLike(String value) {
            addCriterion("updator like", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorNotLike(String value) {
            addCriterion("updator not like", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorIn(List<String> values) {
            addCriterion("updator in", values, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorNotIn(List<String> values) {
            addCriterion("updator not in", values, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorBetween(String value1, String value2) {
            addCriterion("updator between", value1, value2, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorNotBetween(String value1, String value2) {
            addCriterion("updator not between", value1, value2, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatedIsNull() {
            addCriterion("updated is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedIsNotNull() {
            addCriterion("updated is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedEqualTo(Date value) {
            addCriterion("updated =", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedNotEqualTo(Date value) {
            addCriterion("updated <>", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedGreaterThan(Date value) {
            addCriterion("updated >", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedGreaterThanOrEqualTo(Date value) {
            addCriterion("updated >=", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedLessThan(Date value) {
            addCriterion("updated <", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedLessThanOrEqualTo(Date value) {
            addCriterion("updated <=", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedIn(List<Date> values) {
            addCriterion("updated in", values, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedNotIn(List<Date> values) {
            addCriterion("updated not in", values, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedBetween(Date value1, Date value2) {
            addCriterion("updated between", value1, value2, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedNotBetween(Date value1, Date value2) {
            addCriterion("updated not between", value1, value2, "updated");
            return (Criteria) this;
        }

        public Criteria andFaceSetCapacityIsNull() {
            addCriterion("face_set_capacity is null");
            return (Criteria) this;
        }

        public Criteria andFaceSetCapacityIsNotNull() {
            addCriterion("face_set_capacity is not null");
            return (Criteria) this;
        }

        public Criteria andFaceSetCapacityEqualTo(Long value) {
            addCriterion("face_set_capacity =", value, "faceSetCapacity");
            return (Criteria) this;
        }

        public Criteria andFaceSetCapacityNotEqualTo(Long value) {
            addCriterion("face_set_capacity <>", value, "faceSetCapacity");
            return (Criteria) this;
        }

        public Criteria andFaceSetCapacityGreaterThan(Long value) {
            addCriterion("face_set_capacity >", value, "faceSetCapacity");
            return (Criteria) this;
        }

        public Criteria andFaceSetCapacityGreaterThanOrEqualTo(Long value) {
            addCriterion("face_set_capacity >=", value, "faceSetCapacity");
            return (Criteria) this;
        }

        public Criteria andFaceSetCapacityLessThan(Long value) {
            addCriterion("face_set_capacity <", value, "faceSetCapacity");
            return (Criteria) this;
        }

        public Criteria andFaceSetCapacityLessThanOrEqualTo(Long value) {
            addCriterion("face_set_capacity <=", value, "faceSetCapacity");
            return (Criteria) this;
        }

        public Criteria andFaceSetCapacityIn(List<Long> values) {
            addCriterion("face_set_capacity in", values, "faceSetCapacity");
            return (Criteria) this;
        }

        public Criteria andFaceSetCapacityNotIn(List<Long> values) {
            addCriterion("face_set_capacity not in", values, "faceSetCapacity");
            return (Criteria) this;
        }

        public Criteria andFaceSetCapacityBetween(Long value1, Long value2) {
            addCriterion("face_set_capacity between", value1, value2, "faceSetCapacity");
            return (Criteria) this;
        }

        public Criteria andFaceSetCapacityNotBetween(Long value1, Long value2) {
            addCriterion("face_set_capacity not between", value1, value2, "faceSetCapacity");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNull() {
            addCriterion("project_id is null");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNotNull() {
            addCriterion("project_id is not null");
            return (Criteria) this;
        }

        public Criteria andProjectIdEqualTo(Long value) {
            addCriterion("project_id =", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotEqualTo(Long value) {
            addCriterion("project_id <>", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThan(Long value) {
            addCriterion("project_id >", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThanOrEqualTo(Long value) {
            addCriterion("project_id >=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThan(Long value) {
            addCriterion("project_id <", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThanOrEqualTo(Long value) {
            addCriterion("project_id <=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIn(List<Long> values) {
            addCriterion("project_id in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotIn(List<Long> values) {
            addCriterion("project_id not in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdBetween(Long value1, Long value2) {
            addCriterion("project_id between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotBetween(Long value1, Long value2) {
            addCriterion("project_id not between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andFaceSetTypeIsNull() {
            addCriterion("face_set_type is null");
            return (Criteria) this;
        }

        public Criteria andFaceSetTypeIsNotNull() {
            addCriterion("face_set_type is not null");
            return (Criteria) this;
        }

        public Criteria andFaceSetTypeEqualTo(Byte value) {
            addCriterion("face_set_type =", value, "faceSetType");
            return (Criteria) this;
        }

        public Criteria andFaceSetTypeNotEqualTo(Byte value) {
            addCriterion("face_set_type <>", value, "faceSetType");
            return (Criteria) this;
        }

        public Criteria andFaceSetTypeGreaterThan(Byte value) {
            addCriterion("face_set_type >", value, "faceSetType");
            return (Criteria) this;
        }

        public Criteria andFaceSetTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("face_set_type >=", value, "faceSetType");
            return (Criteria) this;
        }

        public Criteria andFaceSetTypeLessThan(Byte value) {
            addCriterion("face_set_type <", value, "faceSetType");
            return (Criteria) this;
        }

        public Criteria andFaceSetTypeLessThanOrEqualTo(Byte value) {
            addCriterion("face_set_type <=", value, "faceSetType");
            return (Criteria) this;
        }

        public Criteria andFaceSetTypeIn(List<Byte> values) {
            addCriterion("face_set_type in", values, "faceSetType");
            return (Criteria) this;
        }

        public Criteria andFaceSetTypeNotIn(List<Byte> values) {
            addCriterion("face_set_type not in", values, "faceSetType");
            return (Criteria) this;
        }

        public Criteria andFaceSetTypeBetween(Byte value1, Byte value2) {
            addCriterion("face_set_type between", value1, value2, "faceSetType");
            return (Criteria) this;
        }

        public Criteria andFaceSetTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("face_set_type not between", value1, value2, "faceSetType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table face_set
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table face_set
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}