package com.sample.servicecomb.provider.model;

import java.io.Serializable;
import java.util.Date;

public class FaceHis implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_his.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_his.face_set_id
     *
     * @mbg.generated
     */
    private String faceSetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_his.face_label_id
     *
     * @mbg.generated
     */
    private String faceLabelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_his.small_obs_url
     *
     * @mbg.generated
     */
    private String smallObsUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_his.similarity
     *
     * @mbg.generated
     */
    private Double similarity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_his.face_date
     *
     * @mbg.generated
     */
    private Date faceDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_his.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_his.age
     *
     * @mbg.generated
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_his.gender
     *
     * @mbg.generated
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_his.hat
     *
     * @mbg.generated
     */
    private String hat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_his.smile
     *
     * @mbg.generated
     */
    private String smile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_his.glass
     *
     * @mbg.generated
     */
    private String glass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_his.camera_id
     *
     * @mbg.generated
     */
    private String cameraId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_his.ori_img_id
     *
     * @mbg.generated
     */
    private String oriImgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_his.original_obs_url
     *
     * @mbg.generated
     */
    private String originalObsUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_his.ori_face_label_id
     *
     * @mbg.generated
     */
    private String oriFaceLabelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table face_his
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_his.id
     *
     * @return the value of face_his.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_his.id
     *
     * @param id the value for face_his.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_his.face_set_id
     *
     * @return the value of face_his.face_set_id
     *
     * @mbg.generated
     */
    public String getFaceSetId() {
        return faceSetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_his.face_set_id
     *
     * @param faceSetId the value for face_his.face_set_id
     *
     * @mbg.generated
     */
    public void setFaceSetId(String faceSetId) {
        this.faceSetId = faceSetId == null ? null : faceSetId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_his.face_label_id
     *
     * @return the value of face_his.face_label_id
     *
     * @mbg.generated
     */
    public String getFaceLabelId() {
        return faceLabelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_his.face_label_id
     *
     * @param faceLabelId the value for face_his.face_label_id
     *
     * @mbg.generated
     */
    public void setFaceLabelId(String faceLabelId) {
        this.faceLabelId = faceLabelId == null ? null : faceLabelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_his.small_obs_url
     *
     * @return the value of face_his.small_obs_url
     *
     * @mbg.generated
     */
    public String getSmallObsUrl() {
        return smallObsUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_his.small_obs_url
     *
     * @param smallObsUrl the value for face_his.small_obs_url
     *
     * @mbg.generated
     */
    public void setSmallObsUrl(String smallObsUrl) {
        this.smallObsUrl = smallObsUrl == null ? null : smallObsUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_his.similarity
     *
     * @return the value of face_his.similarity
     *
     * @mbg.generated
     */
    public Double getSimilarity() {
        return similarity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_his.similarity
     *
     * @param similarity the value for face_his.similarity
     *
     * @mbg.generated
     */
    public void setSimilarity(Double similarity) {
        this.similarity = similarity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_his.face_date
     *
     * @return the value of face_his.face_date
     *
     * @mbg.generated
     */
    public Date getFaceDate() {
        return faceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_his.face_date
     *
     * @param faceDate the value for face_his.face_date
     *
     * @mbg.generated
     */
    public void setFaceDate(Date faceDate) {
        this.faceDate = faceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_his.name
     *
     * @return the value of face_his.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_his.name
     *
     * @param name the value for face_his.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_his.age
     *
     * @return the value of face_his.age
     *
     * @mbg.generated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_his.age
     *
     * @param age the value for face_his.age
     *
     * @mbg.generated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_his.gender
     *
     * @return the value of face_his.gender
     *
     * @mbg.generated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_his.gender
     *
     * @param gender the value for face_his.gender
     *
     * @mbg.generated
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_his.hat
     *
     * @return the value of face_his.hat
     *
     * @mbg.generated
     */
    public String getHat() {
        return hat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_his.hat
     *
     * @param hat the value for face_his.hat
     *
     * @mbg.generated
     */
    public void setHat(String hat) {
        this.hat = hat == null ? null : hat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_his.smile
     *
     * @return the value of face_his.smile
     *
     * @mbg.generated
     */
    public String getSmile() {
        return smile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_his.smile
     *
     * @param smile the value for face_his.smile
     *
     * @mbg.generated
     */
    public void setSmile(String smile) {
        this.smile = smile == null ? null : smile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_his.glass
     *
     * @return the value of face_his.glass
     *
     * @mbg.generated
     */
    public String getGlass() {
        return glass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_his.glass
     *
     * @param glass the value for face_his.glass
     *
     * @mbg.generated
     */
    public void setGlass(String glass) {
        this.glass = glass == null ? null : glass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_his.camera_id
     *
     * @return the value of face_his.camera_id
     *
     * @mbg.generated
     */
    public String getCameraId() {
        return cameraId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_his.camera_id
     *
     * @param cameraId the value for face_his.camera_id
     *
     * @mbg.generated
     */
    public void setCameraId(String cameraId) {
        this.cameraId = cameraId == null ? null : cameraId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_his.ori_img_id
     *
     * @return the value of face_his.ori_img_id
     *
     * @mbg.generated
     */
    public String getOriImgId() {
        return oriImgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_his.ori_img_id
     *
     * @param oriImgId the value for face_his.ori_img_id
     *
     * @mbg.generated
     */
    public void setOriImgId(String oriImgId) {
        this.oriImgId = oriImgId == null ? null : oriImgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_his.original_obs_url
     *
     * @return the value of face_his.original_obs_url
     *
     * @mbg.generated
     */
    public String getOriginalObsUrl() {
        return originalObsUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_his.original_obs_url
     *
     * @param originalObsUrl the value for face_his.original_obs_url
     *
     * @mbg.generated
     */
    public void setOriginalObsUrl(String originalObsUrl) {
        this.originalObsUrl = originalObsUrl == null ? null : originalObsUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_his.ori_face_label_id
     *
     * @return the value of face_his.ori_face_label_id
     *
     * @mbg.generated
     */
    public String getOriFaceLabelId() {
        return oriFaceLabelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_his.ori_face_label_id
     *
     * @param oriFaceLabelId the value for face_his.ori_face_label_id
     *
     * @mbg.generated
     */
    public void setOriFaceLabelId(String oriFaceLabelId) {
        this.oriFaceLabelId = oriFaceLabelId == null ? null : oriFaceLabelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_his
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FaceHis other = (FaceHis) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getFaceSetId() == null ? other.getFaceSetId() == null : this.getFaceSetId().equals(other.getFaceSetId()))
            && (this.getFaceLabelId() == null ? other.getFaceLabelId() == null : this.getFaceLabelId().equals(other.getFaceLabelId()))
            && (this.getSmallObsUrl() == null ? other.getSmallObsUrl() == null : this.getSmallObsUrl().equals(other.getSmallObsUrl()))
            && (this.getSimilarity() == null ? other.getSimilarity() == null : this.getSimilarity().equals(other.getSimilarity()))
            && (this.getFaceDate() == null ? other.getFaceDate() == null : this.getFaceDate().equals(other.getFaceDate()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getAge() == null ? other.getAge() == null : this.getAge().equals(other.getAge()))
            && (this.getGender() == null ? other.getGender() == null : this.getGender().equals(other.getGender()))
            && (this.getHat() == null ? other.getHat() == null : this.getHat().equals(other.getHat()))
            && (this.getSmile() == null ? other.getSmile() == null : this.getSmile().equals(other.getSmile()))
            && (this.getGlass() == null ? other.getGlass() == null : this.getGlass().equals(other.getGlass()))
            && (this.getCameraId() == null ? other.getCameraId() == null : this.getCameraId().equals(other.getCameraId()))
            && (this.getOriImgId() == null ? other.getOriImgId() == null : this.getOriImgId().equals(other.getOriImgId()))
            && (this.getOriginalObsUrl() == null ? other.getOriginalObsUrl() == null : this.getOriginalObsUrl().equals(other.getOriginalObsUrl()))
            && (this.getOriFaceLabelId() == null ? other.getOriFaceLabelId() == null : this.getOriFaceLabelId().equals(other.getOriFaceLabelId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_his
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getFaceSetId() == null) ? 0 : getFaceSetId().hashCode());
        result = prime * result + ((getFaceLabelId() == null) ? 0 : getFaceLabelId().hashCode());
        result = prime * result + ((getSmallObsUrl() == null) ? 0 : getSmallObsUrl().hashCode());
        result = prime * result + ((getSimilarity() == null) ? 0 : getSimilarity().hashCode());
        result = prime * result + ((getFaceDate() == null) ? 0 : getFaceDate().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getAge() == null) ? 0 : getAge().hashCode());
        result = prime * result + ((getGender() == null) ? 0 : getGender().hashCode());
        result = prime * result + ((getHat() == null) ? 0 : getHat().hashCode());
        result = prime * result + ((getSmile() == null) ? 0 : getSmile().hashCode());
        result = prime * result + ((getGlass() == null) ? 0 : getGlass().hashCode());
        result = prime * result + ((getCameraId() == null) ? 0 : getCameraId().hashCode());
        result = prime * result + ((getOriImgId() == null) ? 0 : getOriImgId().hashCode());
        result = prime * result + ((getOriginalObsUrl() == null) ? 0 : getOriginalObsUrl().hashCode());
        result = prime * result + ((getOriFaceLabelId() == null) ? 0 : getOriFaceLabelId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table face_his
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", faceSetId=").append(faceSetId);
        sb.append(", faceLabelId=").append(faceLabelId);
        sb.append(", smallObsUrl=").append(smallObsUrl);
        sb.append(", similarity=").append(similarity);
        sb.append(", faceDate=").append(faceDate);
        sb.append(", name=").append(name);
        sb.append(", age=").append(age);
        sb.append(", gender=").append(gender);
        sb.append(", hat=").append(hat);
        sb.append(", smile=").append(smile);
        sb.append(", glass=").append(glass);
        sb.append(", cameraId=").append(cameraId);
        sb.append(", oriImgId=").append(oriImgId);
        sb.append(", originalObsUrl=").append(originalObsUrl);
        sb.append(", oriFaceLabelId=").append(oriFaceLabelId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}